lib/spark/dsl/entity.ex
lib/spark/dsl/section.ex
lib/spark/options_helpers.ex

improvement: Add typespecs for `Spark.Dsl.Entity` and `Spark.Dsl.Section`.

---

lib/spark/dsl/transformer.ex
test/transfomer_test.exs

I mostly copied the code from here https://github.com/ash-project/spark/blob/66250ad02eb74b309171795499de7c22fe9c44e9/lib/spark/dsl/entity.ex#L80

Apply auto_set_fields when building entities in a transformer

---

lib/spark/code_helpers.ex
test/dsl_test.exs

This adds support for anymous functions with multiple clauses.
Before this change, this code would fail to compile:
```
argument fn
"foo" -> "bar"
_ -> "default"
end
```

Support multiple function clauses in anonymous functions

---

lib/spark/code_helpers.ex

In the unlikely event that an anonymous or captured function has the same content in two or more locations in the same resource we would end up with the same function being defined more than once in each location causing dialyzer errors downstream.
I cannot think of a way to test this sadly.

fix(CodeHelpers): don't generate duplicate functions.

---

lib/spark/dsl/extension.ex
lib/spark/dsl/section.ex
lib/spark/info_generator.ex
test/support/contact.ex

By default the `InfoGenerator` will not generate entity functions for sections with no entities. Now that sections can be marked as patchable the info generator can still generate entity functions in those cases.

fix: Make sections explicitly patchable, improve info generator.

---

lib/spark/dsl.ex

Just a tiny DX improvement because it violated the principal of least surprise for me.

improvement: evaluate `Transformer.eval` chunks in the order they're added.

---

lib/spark/dsl.ex
test/support/contact.ex

This change fixes some DX problems I'm running up against in Cinder.  Also gives some control of the generated module back to the Dsl author.

improvement: Make generated __using__/1 overridable for Dsls.

---

mix.exs

1.0 was only released 2 weeks ago and many libraries haven't updated to it. Since there's no breaking changes in 1.0 supporting both for now shouldn't cause an issue and will make spark easier to add in other projects.

fix: Relax nimble_options dependency

---

lib/spark/dsl.ex
lib/spark/dsl/extension.ex

`Exception.exception?` [is deprecated](https://hexdocs.pm/elixir/1.12/Exception.html#exception?/1) and [will be removed in elixir 1.15](https://github.com/elixir-lang/elixir/blob/a64d42f5d3cb6c32752af9d3312897e8cd5bb7ec/lib/elixir/lib/exception.ex#L49)
`Kernel.is_exception` has been available [since elixir 1.11](https://hexdocs.pm/elixir/1.14/Kernel.html#is_exception/1), and [since spark requires elixir ~> 1.13](https://github.com/ash-project/spark/blob/main/mix.exs#L12) we are safe to depend on it.

fix: swap `Exception.exception?` for `Kernel.is_exception`

---

lib/spark/dsl/extension.ex

Not sure how the tests passed on this one!?

fix: don't explode for non-tuple argument values.

---

lib/spark/dsl/entity.ex
lib/spark/dsl/transformer.ex
test/transformer_test.exs

Entities without an `__identifier__` field should cause Spark to fail rather than silently break the target struct's contracts.

fix(Entity): don't ever use `Map.put/3` to set an entity's `__identifier__`.

---

lib/spark/dsl/extension.ex
test/support/contact/contact.ex

The idea is to open up patching possibilities. Right now unless a section explicitly sets `patchable?: true` it is forbidden to add any entities with patches to it.
This change allows adding entities that have the same target as at least one of preexisting entities in a section.
It will allow to easily provide shortcut/alias entities with extensions in ash-compatible way, so that auto-complete and `do end` syntax for options can work out of box for those aliases.
`patchable?: true` still needs to be set to allow adding entities with arbitrary targets.
Don't know if I can put check mark on unit tests, but the only place in tests where `patchable?: true` was used can now omit that option since a test extension was adding the same target thing (preset).

improvement: allow `Patch.AddEntity` if a same-target entity exists

---

lib/spark/dsl/extension.ex

I don't know if this is intentional but the latest version of the documentation of spark in the Dsl.Extensions page is displayed like this
I though that maybe it should be displayed like this instead

fix: code highlight error

---

lib/spark/types.ex

From comment in https://github.com/ash-project/ash/pull/700: changes order for `:wrap_list` doc from `list(x) | x` to `x | list(x)`.
No idea if it is a "fix" or "improvement", put it in improvement to be on a safer side.

improvement: change `:wrap_list` doc to `x | list(x)`

---

lib/spark/cheat_sheet.ex

As `\` is an escape character, to render a literal `\` you need two - so to render two, you need four
Noticed when browsing docs for AshAuthentication, eg. https://hexdocs.pm/ash_authentication/dsl-ashauthentication-strategy-password.html#authentication-strategies-password

fix: Ensure `\\` for default argument values are rendered correctly in generated guides

---

lib/spark/options_helpers.ex
lib/spark/types.ex

- Out of three types with support for nested keyed schemas (`keyword_list`, `non_empty_keyword_list` and `map`) only `keyword_list` had `doc_type` [case](https://github.com/ash-project/spark/blob/a843a3c202cc622085e141aaf3643ceccaa19152/lib/spark/types.ex#L22-L25) for nested schema. It was incorrect. So fixed that one and added support for other two.
- There was a case for `doc_type({:keyword_list, value_type})` (where `value_type` is a type, not a schema), but such type construct does not exist (at least it is not listed in typespecs). Removed it.
- Changed `Keyword.t` to simple `keyword` to match other type names.
- Offtop but there were three types of writing any: `any`, `"any"` and `any()`. Changed others to use the first variant.

improvement: working `doc_type` for nested schemas

---

lib/spark/info_generator.ex
lib/spark/options_helpers.ex
lib/spark/types.ex

`:in` and `:one_of` work with a list of values, not a list of types. Corrected typespec and `sanitize_type` logic.
Also made naming of values list consistent - it had `values`, `types`, `choices`, `options`. Made all to use `values`.

fix: correct typespec/sanitisation for :in and :one_of

---

lib/spark/formatter.ex

`Spark.Formatter`'s `parse_extensions` extension function expects the config for a specific module but loads the top level config. 
At the moment, it attempts to load the extensions from the top-level config:
```elixir
config :spark, :formatter,
remove_parens?: true,
"Ash.Resource": [
section_order: [
:resource,
:postgres,
:attributes,
:relationships,
:aggregates,
:calculations
]
],
"MyApp.Resource": [
type: Ash.Resource,
extensions: [MyApp.ResourceExtension],
section_order: [...]
]
```
It should instead load the extensions from the module we are formatting eg:
```elixir
[
type: Ash.Resource,
extensions: [MyApp.ResourceExtension],
section_order: [...]
]
```

Update Spark.Formatter to respect `extensions` list

---

test/cross_extension_recursive_patch_test.exs

This is a reproduction of a bug where patched entities cannot be fully recursive of other extension's entities.

chore: Add reproduction for recursive cross-extension entity bug.

---

lib/spark/info_generator.ex

Fix Spark.InfoGenerator

---

lib/spark/dsl.ex
lib/spark/dsl/verifiers/verify_entity_uniqueness.ex
lib/spark/elixir_sense/plugin.ex
lib/spark/formatter.ex

Drop support for elixir < 1.15

---

lib/spark/code_helpers.ex

md5 accepts iodata, so it is more performant to use term_to_iovec. Just a micro optimization

Use term_to_iovec instead of term_to_binary

---

lib/spark/dsl.ex

Simply hiding the DSL functions that get added from generated documentation.

docs: don't document dsl functions

---

lib/spark/formatter.ex

We have something like
```elixir
defmodule MyApp.Post do
use MyApp.Resource, comment: "blah blah"
end
```
and the `"blah blah"` is passed as an extension to spark formatter.
so before calling `Code.ensure_compiled/1`, 
`is_atom/1` or any other type validation should be performed, I think.

fix: ensure atom before check compiled

---

lib/spark/options/docs.ex
lib/spark/options/options.ex
test/options/impl_validator_test.exs

`:impl` option type is similar to `:protocol`, but accepts module name instead of concrete value.

add :impl option type

---

lib/mix/tasks/spark.cheat_sheets.ex
lib/spark/cheat_sheet.ex

In many cases when the target is just a simple struct and there is really nothing to document. But `@moduledoc false` causes warnings about referencing hidden modules. `--no-introspection` option  instructs `mix spark.cheat_sheets`  to skip generation of Introspection sections

disable introspection section in cheatsheets if target module is not documented

---

test/dsl_test.exs

When a DSL section is empty the schema validation should still set the options to their defaults for introspection.

chore: Add failing tests for section option default bug.

---

lib/spark/dsl/transformer.ex

Not sure if it's bug, feel free to close.

doc: Use full module name (`Spark.Dsl.Transformer`) in `eval/3` doc

---

documentation/tutorials/get-started-with-spark.md

* Inconsistency in defined code interface (`process` vs `transform`)
* missing `end` delimiter in `Validator` code

fix: example in getting started guide

---

documentation/tutorials/get-started-with-spark.md

Completed the `process` -> `transform` find and replace by fixing missed instances.
However, I'm now wondering if retaining the original `process` name might have been better to clearly distinguish it from the `transform` callback function within the `Transformer` module.

Fix missing find and replace

---

lib/spark/options/options.ex
test/spark_test.exs

ehh..? i dunno what to check :p

add `:number` type to handle integers _or_ floats

---

documentation/how_to/use-source-annotations.md
documentation/how_to/writing-extensions.md
documentation/tutorials/get-started-with-spark.md
lib/mix/tasks/spark.cheat_sheets_in_search.ex
lib/spark/cheat_sheet.ex
lib/spark/dsl.ex
lib/spark/dsl/entity.ex
lib/spark/dsl/entity/meta.ex
lib/spark/dsl/extension.ex
lib/spark/dsl/extension/entity.ex
lib/spark/dsl/extension/entity_option.ex
lib/spark/dsl/extension/section_option.ex
lib/spark/dsl/transformer.ex
lib/spark/dsl/verifier.ex
lib/spark/dsl/verifiers/verify_entity_uniqueness.ex
lib/spark/error/dsl_error.ex
lib/spark/options/options.ex
lib/spark/options/validator.ex
lib/spark/warning.ex
mix.exs
test/cross_extension_recursive_patch_test.exs
test/dsl_test.exs
test/support/contact/contact.ex
test/support/contact/verifiers/verify_not_gandalf.ex
test/support/recursive/atom.ex
test/support/recursive/step.ex
usage-rules.md

Implements #65
* Provides Introspection Function to retrieve `erl_anno` for sections, section options, entities, and entity properties
* Adds location to DslError and provides it where feasible
* Adds `Spark.Warning` (internal) for emitting warnings. Supports intentional locations as well as stacktraces.
* End Of Expression Locations require `token_metadata` parser option to be enabled.
* Start Location Column is not tracked since that would require Elixir to pass `column` meta into `Macro.Env`.
* Option End Of Expression is not tracked since the value is expanded and the macro receives the value and not an AST.
Leave anything that you believe does not apply unchecked.

Record Source Annotations

---

lib/spark/dsl/extension.ex

https://discord.com/channels/711271361523351632/1037049265836535868/1420674638622752788
```
== Compilation error in file lib/ash_authentication/strategies/magic_link.ex ==
** (UndefinedFunctionError) function AshAuthentication.Strategy.MagicLink.__struct__/0 is undefined (function not available)
AshAuthentication.Strategy.MagicLink.__struct__()
/Users/.../code/kloevaa/deps/spark/lib/spark/dsl/extension.ex:1515: (module)
(spark 2.3.3) lib/spark/dsl/extension.ex:1253: Spark.Dsl.Extension.build_entity/8
could not compile dependency :ash_authentication, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ash_authentication --force", update it with "mix deps.update ash_authentication" or clean it with "mix deps.clean …
```

Verify Metadata Struct Fields after Compilation

---

lib/spark/dsl/entity.ex
lib/spark/dsl/extension.ex
test/dsl_validation_test.exs

Fixes #215 
Instead of adding an additional `List.wrap`, I thought it might be a good idea to perform validation and transformation early on. This PR removes one List.wrap :P
I believe this might cause a slow down of consumers, as we potentially recurse the entity tree repeatedly and don't cache the transformation results.
As a demo, this implements #215. But more validations could be added to catch common misconfigurations. (E.g. to also allow sub-entities without keys, by transforming `entities: [@child]` to `entities: [child_entity_name: [@child]]`.
Please let me know if this is feasible/wanted - otherwise I'll just add the List.wrap :)
Implements early validation of DSL entity structures to catch configuration errors at compile time rather than runtime. Key improvements:
- Add …

Add DSL entity validation and transformation

---

lib/spark/dsl/entity.ex
lib/spark/dsl/extension.ex
test/dsl_validation_test.exs

Fixes the failing validation test (https://github.com/ash-project/spark/actions/runs/18011100579/job/51243787914). Before, set_docs would be called on the un-transformed sections.
The `validate_and_transform_*` functions are now all in `extension.ex`. 
This should be cleaner now. I'm not sure if moving `set_docs` into the`extension` module is a problem.
Leave anything that you believe does not apply unchecked.

fix: hoist validation and transformation to top of call chain
